[toolchain]
channel = "nightly"
profile = "minimal"
components = [
    "rustc",
    "cargo",
    "clippy",
    "rustfmt",
    "rust-analyzer",
    "miri",
    "rust-src",
]
targets = [
    "wasm32-unknown-unknown",
]
